'use client';

// =============================================================================
// ApprovalDrawer — Right-side overlay for Block Disconnection Memo Review
// =============================================================================
// Width: 480px, full-height, #161B22 bg, left border 2px #30363D.
// Accessible from Dashboard and Workspace without page navigation.
// =============================================================================

import { useState, useMemo } from 'react';
import { useOperationalStore } from '@/store/operationalStore';
import { useAuditStore } from '@/store/auditStore';
import { useSessionStore } from '@/store/sessionStore';
import type { BlockProposal, ShapExplanation, PunctualityImpact } from '@/types/railway';
import GSRChecklist from './GSRChecklist';
import ShapExplanationCard from './ShapExplanationCard';
import PunctualityTable from './PunctualityTable';
import DigitalSignatureForm from './DigitalSignatureForm';
import AuditMiniLog from './AuditMiniLog';
import { X, Copy, Check, FileText } from 'lucide-react';

interface ApprovalDrawerProps {
  isOpen: boolean;
  proposalId: string | null;
  onClose: () => void;
}

export default function ApprovalDrawer({
  isOpen,
  proposalId,
  onClose,
}: ApprovalDrawerProps) {
  const proposals = useOperationalStore((s) => s.proposals);
  const updateProposalStatus = useOperationalStore((s) => s.updateProposalStatus);
  const trains = useOperationalStore((s) => s.trains);
  const addAuditEntry = useAuditStore((s) => s.addEntry);
  const auditEntries = useAuditStore((s) => s.entries);
  const user = useSessionStore((s) => s.user);
  const sessionId = useSessionStore((s) => s.sessionId);

  const [copied, setCopied] = useState(false);
  const [successBanner, setSuccessBanner] = useState<string | null>(null);

  const proposal = useMemo(() => {
    if (!proposalId) return null;
    return proposals.find((p) => p.proposalId === proposalId) || null;
  }, [proposalId, proposals]);

  // Derive Audit entries for this specific proposal
  const proposalAuditEntries = useMemo(() => {
    if (!proposalId) return [];
    return auditEntries.filter((e) => e.targetId === proposalId);
  }, [proposalId, auditEntries]);

  // Derive SHAP explanation
  const shapExplanation: ShapExplanation = useMemo(() => {
    if (!proposal) {
      return {
        topFeatures: [],
        baseScore: 0.5,
        finalScore: 0.5,
        narrativeSummary: 'No explanation available.',
      };
    }
    return {
      topFeatures: [
        {
          featureName: 'asset_condition_degradation',
          featureValue: 'CLASS_B',
          shapValue: 0.24,
          humanLabel: 'Track geometry index below maintenance threshold',
        },
        {
          featureName: 'joint_block_efficiency',
          featureValue: proposal.blockType,
          shapValue: proposal.blockType === 'JOINT' ? 0.18 : 0.02,
          humanLabel: proposal.blockType === 'JOINT' ? 'Bundled joint window saves 240 train-minutes' : 'Single department window',
        },
        {
          featureName: 'traffic_impact_cost',
          featureValue: proposal.affectedTrains.length,
          shapValue: -0.12,
          humanLabel: `Impacts ${proposal.affectedTrains.length} scheduled services`,
        },
      ],
      baseScore: 0.5,
      finalScore: proposal.aiPriorityScore,
      narrativeSummary: `Priority score ${proposal.aiPriorityScore.toFixed(2)} generated by XGBoost block model. Recommended execution during off-peak interval with joint OHE/Civil synchronization.`,
    };
  }, [proposal]);

  // Derive Punctuality Impacts
  const punctualityImpacts: PunctualityImpact[] = useMemo(() => {
    if (!proposal) return [];
    return proposal.affectedTrains.map((tn) => {
      const train = trains.find((t) => t.trainNumber === tn);
      return {
        trainNumber: tn,
        trainName: train?.trainName || 'Express Service',
        scheduledTime: train?.scheduledDeparture || '',
        predictedTime: train?.scheduledArrival || '',
        deltaMinutes: train?.priority === 1 ? 4 : 8,
        priority: (train?.priority || 2) as 1 | 2 | 3,
      };
    });
  }, [proposal, trains]);

  if (!isOpen || !proposal) return null;

  const handleCopyId = () => {
    navigator.clipboard.writeText(proposal.proposalId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const isBlockedByGSR = proposal.gsrCompliance.some((c) => c.status === 'FAIL');

  const handleApprove = async (employeeId: string, pin: string) => {
    const memoId = `MEMO-NR-GZB-${Date.now().toString().slice(-6)}`;

    // Update in store
    updateProposalStatus(proposal.proposalId, 'APPROVED');

    // Create Audit entry with real chained hash
    await addAuditEntry(
      user?.userId || 'USR-SC-001',
      user?.role || 'ROLE_SC',
      'BLOCK_APPROVED',
      proposal.proposalId,
      {
        status: { before: proposal.status, after: 'APPROVED' },
        digitalSignature: employeeId,
        memoReference: memoId,
        grantedStart: proposal.requestedStart,
        grantedDuration: proposal.requestedDuration,
      },
      sessionId
    );

    setSuccessBanner(`Memo Approved — Reference: ${memoId}`);
    setTimeout(() => {
      setSuccessBanner(null);
      onClose();
    }, 3000);
  };

  const handleReject = async (employeeId: string, pin: string, comment: string) => {
    updateProposalStatus(proposal.proposalId, 'REJECTED');

    await addAuditEntry(
      user?.userId || 'USR-SC-001',
      user?.role || 'ROLE_SC',
      'BLOCK_REJECTED',
      proposal.proposalId,
      {
        status: { before: proposal.status, after: 'REJECTED' },
        rejectedBy: employeeId,
        mandatoryComment: comment,
      },
      sessionId
    );

    setSuccessBanner(`Proposal Rejected — Audit logged.`);
    setTimeout(() => {
      setSuccessBanner(null);
      onClose();
    }, 3000);
  };

  return (
    <div
      style={{
        position: 'fixed',
        top: 0,
        right: 0,
        width: 'var(--drawer-width)',
        height: '100vh',
        background: 'var(--color-bg-elevated)',
        borderLeft: '2px solid var(--color-border-default)',
        boxShadow: '-4px 0 24px rgba(0, 0, 0, 0.6)',
        zIndex: 100,
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: 'var(--spacing-4)',
          borderBottom: '1px solid var(--color-border-default)',
          background: 'var(--color-bg-primary)',
          display: 'flex',
          alignItems: 'flex-start',
          justifyContent: 'space-between',
        }}
      >
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--spacing-2)' }}>
            <FileText size={18} style={{ color: 'var(--color-accent-operational)' }} />
            <h2
              style={{
                fontFamily: 'var(--font-reading)',
                fontSize: 'var(--text-base)',
                fontWeight: 700,
                color: 'var(--color-text-primary)',
              }}
            >
              Block Disconnection Memo
            </h2>
            <span
              className="status-tag"
              style={{
                background:
                  proposal.status === 'APPROVED'
                    ? 'rgba(35, 134, 54, 0.2)'
                    : 'rgba(210, 153, 34, 0.2)',
                color:
                  proposal.status === 'APPROVED'
                    ? 'var(--color-accent-success)'
                    : 'var(--color-accent-warning)',
              }}
            >
              {proposal.status}
            </span>
          </div>

          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 'var(--spacing-2)',
              marginTop: 'var(--spacing-1)',
              fontSize: 'var(--text-xs)',
              color: 'var(--color-text-secondary)',
            }}
          >
            <span className="font-mono" style={{ color: 'var(--color-text-mono)' }}>
              {proposal.proposalId}
            </span>
            <button
              onClick={handleCopyId}
              style={{
                background: 'transparent',
                border: 'none',
                color: 'var(--color-text-secondary)',
                cursor: 'pointer',
                padding: 0,
              }}
              title="Copy ID"
            >
              {copied ? <Check size={12} style={{ color: 'var(--color-accent-success)' }} /> : <Copy size={12} />}
            </button>
            <span>|</span>
            <span className={`dept-tag dept-tag--${proposal.department.toLowerCase()}`}>
              {proposal.department}
            </span>
            <span>|</span>
            <span>By: {proposal.submittedBy}</span>
          </div>
        </div>

        <button
          onClick={onClose}
          id="close-drawer-btn"
          style={{
            background: 'transparent',
            border: 'none',
            color: 'var(--color-text-secondary)',
            cursor: 'pointer',
            padding: 4,
          }}
        >
          <X size={18} />
        </button>
      </div>

      {/* Success alert banner */}
      {successBanner && (
        <div
          style={{
            padding: 'var(--spacing-3)',
            background: 'rgba(35, 134, 54, 0.2)',
            borderBottom: '1px solid var(--color-accent-success)',
            color: 'var(--color-accent-success)',
            fontSize: 'var(--text-sm)',
            fontWeight: 600,
            textAlign: 'center',
          }}
        >
          {successBanner}
        </div>
      )}

      {/* Scrollable Interior */}
      <div
        style={{
          flex: 1,
          overflowY: 'auto',
          padding: 'var(--spacing-4)',
          display: 'flex',
          flexDirection: 'column',
          gap: 'var(--spacing-4)',
        }}
      >
        {/* SECTION A — BLOCK PARAMETERS */}
        <div>
          <h3
            style={{
              fontSize: 'var(--text-xs)',
              fontWeight: 700,
              color: 'var(--color-text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              marginBottom: 'var(--spacing-2)',
            }}
          >
            Section A — Operational Parameters
          </h3>
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: '1fr 1fr',
              gap: 'var(--spacing-2)',
              background: 'var(--color-bg-primary)',
              padding: 'var(--spacing-3)',
              borderRadius: 'var(--radius-panel)',
              border: '1px solid var(--color-border-default)',
              fontSize: 'var(--text-xs)',
            }}
          >
            <div>
              <span style={{ color: 'var(--color-text-secondary)' }}>Section Span:</span>
              <div className="font-mono" style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>
                km {proposal.section.fromKm} to km {proposal.section.toKm}
              </div>
            </div>

            <div>
              <span style={{ color: 'var(--color-text-secondary)' }}>Track Line:</span>
              <div style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>
                {proposal.section.lineType} LINE
              </div>
            </div>

            <div>
              <span style={{ color: 'var(--color-text-secondary)' }}>Window Start:</span>
              <div className="font-mono" style={{ fontWeight: 600, color: 'var(--color-text-mono)' }}>
                {new Date(proposal.requestedStart).toLocaleTimeString('en-IN', {
                  hour: '2-digit',
                  minute: '2-digit',
                  timeZone: 'Asia/Kolkata',
                })}{' '}
                IST
              </div>
            </div>

            <div>
              <span style={{ color: 'var(--color-text-secondary)' }}>Requested Duration:</span>
              <div className="font-mono" style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>
                {proposal.requestedDuration} Minutes
              </div>
            </div>

            <div style={{ gridColumn: 'span 2' }}>
              <span style={{ color: 'var(--color-text-secondary)' }}>Activity / Equipment:</span>
              <div style={{ color: 'var(--color-text-primary)', marginTop: 2 }}>
                {proposal.equipmentActivity}
              </div>
            </div>
          </div>
        </div>

        {/* SECTION B — G&SR COMPLIANCE CHECKLIST */}
        <div>
          <h3
            style={{
              fontSize: 'var(--text-xs)',
              fontWeight: 700,
              color: 'var(--color-text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              marginBottom: 'var(--spacing-2)',
            }}
          >
            Section B — G&amp;SR Compliance Verification
          </h3>
          <GSRChecklist checks={proposal.gsrCompliance} />
        </div>

        {/* SECTION C — AI EXPLAINABILITY CARD */}
        <div>
          <h3
            style={{
              fontSize: 'var(--text-xs)',
              fontWeight: 700,
              color: 'var(--color-text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              marginBottom: 'var(--spacing-2)',
            }}
          >
            Section C — Optimization Reasoning
          </h3>
          <ShapExplanationCard explanation={shapExplanation} />
        </div>

        {/* SECTION D — PUNCTUALITY IMPACT */}
        <div>
          <h3
            style={{
              fontSize: 'var(--text-xs)',
              fontWeight: 700,
              color: 'var(--color-text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              marginBottom: 'var(--spacing-2)',
            }}
          >
            Section D — Train Punctuality Impact
          </h3>
          <PunctualityTable impacts={punctualityImpacts} />
        </div>

        {/* SECTION E — DIGITAL SIGNATURE & APPROVAL ACTIONS */}
        {proposal.status !== 'APPROVED' && proposal.status !== 'REJECTED' && (
          <div>
            <h3
              style={{
                fontSize: 'var(--text-xs)',
                fontWeight: 700,
                color: 'var(--color-text-secondary)',
                textTransform: 'uppercase',
                letterSpacing: '0.06em',
                marginBottom: 'var(--spacing-2)',
              }}
            >
              Section E — Authorization Workflow
            </h3>
            <DigitalSignatureForm
              proposalId={proposal.proposalId}
              isBlockedByGSR={isBlockedByGSR}
              onApprove={handleApprove}
              onReject={handleReject}
            />
          </div>
        )}

        {/* SECTION F — AUDIT TRAIL MINI-LOG */}
        <div>
          <h3
            style={{
              fontSize: 'var(--text-xs)',
              fontWeight: 700,
              color: 'var(--color-text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: '0.06em',
              marginBottom: 'var(--spacing-2)',
            }}
          >
            Section F — Audit Record &amp; Hash Chain
          </h3>
          <AuditMiniLog entries={proposalAuditEntries} />
        </div>
      </div>
    </div>
  );
}
